name: Findutils Arch Linux CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          pacman -Syu --noconfirm base-devel
          cd uufu
          yes|PKGDEST=/tmp/uufu makepkg --noconfirm -s
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uufu
          path: /tmp/uufu
