name: Procps Arch Linux CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: |
          pacman -Syu --noconfirm base-devel
          useradd user -mG wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R .
          cd uupr
          su user -c "yes|PKGDEST=/tmp/uupr makepkg --noconfirm -s"
      - name: Archive the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: uupr
          path: /tmp/uupr
